- hosts: all
  tasks:
#  - name: Copy file with owner and permissions
 #   copy:
  #    src: /mongo.repo(repo file name that you have to create as shown above)
   #   dest: /etc/yum.repos.d/
  - name: Install mongodb-org package
    yum:
     name: mongodb-org
     state: present

  - name: Start the service
    service:
      name: mongod
      state: started
